GHC 9.4 Support
sol/doctest pull request #375
Opened 2022-05-19 03:24 UTC by parsonsmatt

Looks like this one might be more complicated.

Test suite fails from running `cabal test` with a `ghcup` provided GHC 9.4:

```

Failures:

  test/MainSpec.hs:128:7:
  1) Main, doctest as a runner for QuickCheck properties, runs a boolean property
       property-bool ["Foo.hs"]
       expected: Examples: 1  Tried: 1  Errors: 0  Failures: 0
        but got: Examples: 1  Tried: 1  Errors: 0  Failures: 1

  To rerun use: --match "/Main/doctest as a runner for QuickCheck properties/runs a boolean property/"

  test/MainSpec.hs:132:7:
  2) Main, doctest as a runner for QuickCheck properties, runs an explicitly quantified property
       property-quantified ["Foo.hs"]
       expected: Examples: 1  Tried: 1  Errors: 0  Failures: 0
        but got: Examples: 1  Tried: 1  Errors: 0  Failures: 1

  To rerun use: --match "/Main/doctest as a runner for QuickCheck properties/runs an explicitly quantified property/"

  test/MainSpec.hs:136:7:
  3) Main, doctest as a runner for QuickCheck properties, runs an implicitly quantified property
       property-implicitly-quantified ["Foo.hs"]
       expected: Examples: 1  Tried: 1  Errors: 0  Failures: 0
        but got: Examples: 1  Tried: 1  Errors: 0  Failures: 1

  To rerun use: --match "/Main/doctest as a runner for QuickCheck properties/runs an implicitly quantified property/"

  test/MainSpec.hs:144:7:
  4) Main, doctest as a runner for QuickCheck properties, runs a boolean property with an explicit type signature
       property-bool-with-type-signature ["Foo.hs"]
       expected: Examples: 1  Tried: 1  Errors: 0  Failures: 0
        but got: Examples: 1  Tried: 1  Errors: 0  Failures: 1

  To rerun use: --match "/Main/doctest as a runner for QuickCheck properties/runs a boolean property with an explicit type signature/"

  test/MainSpec.hs:148:7:
  5) Main, doctest as a runner for QuickCheck properties, runs $setup before each property
       property-setup ["Foo.hs"]
       expected: Examples: 3  Tried: 3  Errors: 0  Failures: 0
        but got: Examples: 3  Tried: 1  Errors: 0  Failures: 1

  To rerun use: --match "/Main/doctest as a runner for QuickCheck properties/runs $setup before each property/"

  test/PropertySpec.hs:21:32:
  6) Property.runProperty reports a failing property
       expected: Failure "*** Failed! Falsified (after 1 test):"
        but got: Failure "\n<interactive>:32:3: error:\n    Variable not in scope:\n      polyQuickCheck\n        :: Language.Haskell.TH.Syntax.Name\n           -> Language.Haskell.TH.Lib.Internal.ExpQ"

  To rerun use: --match "/Property/runProperty/reports a failing property/"

  test/PropertySpec.hs:24:31:
  7) Property.runProperty runs a Bool property
       expected: Success
        but got: Failure "\n<interactive>:32:3: error:\n    Variable not in scope:\n      polyQuickCheck\n        :: Language.Haskell.TH.Syntax.Name\n           -> Language.Haskell.TH.Lib.Internal.ExpQ"

  To rerun use: --match "/Property/runProperty/runs a Bool property/"

  test/PropertySpec.hs:27:39:
  8) Property.runProperty runs a Bool property with an explicit type signature
       expected: Success
        but got: Failure "\n<interactive>:32:3: error:\n    Variable not in scope:\n      polyQuickCheck\n        :: Language.Haskell.TH.Syntax.Name\n           -> Language.Haskell.TH.Lib.Internal.ExpQ"

  To rerun use: --match "/Property/runProperty/runs a Bool property with an explicit type signature/"

  test/PropertySpec.hs:30:66:
  9) Property.runProperty runs an implicitly quantified property
       expected: Success
        but got: Failure "\n<interactive>:32:3: error:\n    Variable not in scope:\n      polyQuickCheck\n        :: Language.Haskell.TH.Syntax.Name\n           -> Language.Haskell.TH.Lib.Internal.ExpQ"

  To rerun use: --match "/Property/runProperty/runs an implicitly quantified property/"

  test/PropertySpec.hs:42:64:
  10) Property.runProperty runs an implicitly quantified property even with GHC 7.4
       expected: Success
        but got: Failure "\n<interactive>:32:3: error:\n    Variable not in scope:\n      polyQuickCheck\n        :: Language.Haskell.TH.Syntax.Name\n           -> Language.Haskell.TH.Lib.Internal.ExpQ"

  To rerun use: --match "/Property/runProperty/runs an implicitly quantified property even with GHC 7.4/"

  test/PropertySpec.hs:46:74:
  11) Property.runProperty runs an explicitly quantified property
       expected: Success
        but got: Failure "\n<interactive>:32:3: error:\n    Variable not in scope:\n      polyQuickCheck\n        :: Language.Haskell.TH.Syntax.Name\n           -> Language.Haskell.TH.Lib.Internal.ExpQ"

  To rerun use: --match "/Property/runProperty/runs an explicitly quantified property/"

  test/PropertySpec.hs:49:48:
  12) Property.runProperty allows to mix implicit and explicit quantification
       expected: Success
        but got: Failure "\n<interactive>:32:3: error:\n    Variable not in scope:\n      polyQuickCheck\n        :: Language.Haskell.TH.Syntax.Name\n           -> Language.Haskell.TH.Lib.Internal.ExpQ"

  To rerun use: --match "/Property/runProperty/allows to mix implicit and explicit quantification/"

  test/PropertySpec.hs:52:34:
  13) Property.runProperty reports the value for which a property fails
       expected: Failure "*** Failed! Falsified (after 1 test):\n0"
        but got: Failure "\n<interactive>:32:3: error:\n    Variable not in scope:\n      polyQuickCheck\n        :: Language.Haskell.TH.Syntax.Name\n           -> Language.Haskell.TH.Lib.Internal.ExpQ"

  To rerun use: --match "/Property/runProperty/reports the value for which a property fails/"

  test/PropertySpec.hs:56:75:
  14) Property.runProperty reports the values for which a property that takes multiple arguments fails
       expected: ["False", "0", "\"\""]
        but got: ["<interactive>:32:3: error:", "    Variable not in scope:", "      polyQuickCheck", "        :: Language.Haskell.TH.Syntax.Name", "           -> Language.Haskell.TH.Lib.Internal.ExpQ"]

  To rerun use: --match "/Property/runProperty/reports the values for which a property that takes multiple arguments fails/"

  test/RunSpec.hs:87:5:
  15) Run.doctest prints verbose description of a property
       uncaught exception: ExitCode
       ExitFailure 1

  To rerun use: --match "/Run/doctest/prints verbose description of a property/"

  test/RunSpec.hs:116:5:
  16) Run.doctest can deal with potentially problematic GHC options
       uncaught exception: ExitCode
       ExitFailure 1

  To rerun use: --match "/Run/doctest/can deal with potentially problematic GHC options/"

Randomized with seed 108586937

Finished in 9.8986 seconds
177 examples, 16 failures

Test suite spec: FAIL
Test suite logged to:
/home/matt/Projects/doctest/dist-newstyle/build/x86_64-linux/ghc-9.2.2/doctest-0.20.0/t/spec/test/doctest-0.20.0-spec.log
0 of 1 test suites (0 of 1 test cases) passed.
cabal: Tests failed for test:spec from doctest-0.20.0.
```

2022-05-19 12:17 UTC, sol commented
@parsonsmatt did you use `cabal exec` when running the test? If not, that's probably the issue. We need QuickCheck in scope.

Let's wait for the CI result.

2022-05-19 12:34 UTC, sol requested changes
This looks great.  Please also bump the package version.  If you do that, a release will happen automatically once this hits the `main` branch.

2022-05-19 14:45 UTC, parsonsmatt commented
Ah, shoot, I was building with GHC 9.2 -_-

Looks like 9.4 has some differences in `DocDecl` and related things that I need to work on.

2022-05-19 15:47 UTC, parsonsmatt commented
Alright, got it building with GHC 9.4, but failing some tests:

```
Failures:

  test/ExtractSpec.hs:40:35:
  1) Extract.extract extracts documentation from argument list
       expected: [Module {moduleName = "Foo", moduleSetup = Nothing, moduleContent = [" doc for arg1"," doc for arg2"]}]
        but got: [Module {moduleName = "Foo", moduleSetup = Nothing, moduleContent = []}]

  To rerun use: --match "/Extract/extract/extracts documentation from argument list/"

  test/ExtractSpec.hs:46:37:
  2) Extract.extract extracts documentation from the argument list of a type class function
       expected: [Module {moduleName = "Foo", moduleSetup = Nothing, moduleContent = [" foo"," bar"]}]
        but got: [Module {moduleName = "Foo", moduleSetup = Nothing, moduleContent = []}]

  To rerun use: --match "/Extract/extract/extracts documentation from the argument list of a type class function/"

  test/MainSpec.hs:70:7:
  3) Main.doctest testCommentLocation
       . ["testCommentLocation/Foo.hs"]
       expected: Examples: 11  Tried: 11  Errors: 0  Failures: 0
        but got: Examples: 9  Tried: 9  Errors: 0  Failures: 0

  To rerun use: --match "/Main/doctest/testCommentLocation/"

  test/MainSpec.hs:90:7:
  4) Main.doctest testDocumentationForArguments
       testDocumentationForArguments ["Fib.hs"]
       expected: Examples: 1  Tried: 1  Errors: 0  Failures: 0
        but got: Examples: 0  Tried: 0  Errors: 0  Failures: 0

  To rerun use: --match "/Main/doctest/testDocumentationForArguments/"

  test/RunSpec.hs:136:42:
  5) Run.doctestWithOptions, on parse error, prints a useful error message
       expected: "\nFoo.hs:6:1: error:\n    parse error (possibly incorrect indentation or mismatched brackets)\n"
        but got: "\n\ESC[;1mFoo.hs:6:1: \ESC[;1m\ESC[31merror:\ESC[0m\ESC[0m\ESC[;1m\ESC[0m\ESC[0m\ESC[;1m\n    parse error (possibly incorrect indentation or mismatched brackets)\ESC[0m\ESC[0m\n"

  To rerun use: --match "/Run/doctestWithOptions/on parse error/prints a useful error message/"

Randomized with seed 2021858890

Finished in 11.5832 seconds
177 examples, 5 failures
Test suite spec: FAIL
Test suite logged to:
/home/matt/Projects/doctest/dist-newstyle/build/x86_64-linux/ghc-9.4.0.20220501/doctest-0.20.0/t/spec/test/doctest-0.20.0-spec.log
0 of 1 test suites (0 of 1 test cases) passed.
cabal: Tests failed for test:spec from doctest-0.20.0.
```

2022-05-19 21:13 UTC, parsonsmatt commented
Yeah. I'm not sure how to enable that since it's an alpha prerelease.

2022-05-28 20:49 UTC, andreasabel commented on src/Extract.hs
> +      hsc_env' <- liftIO (initializePlugins hsc_env)
This code looks idential to the one in conditional for GHC >= 9.1 (`__GLASGOW_HASKELL__ >= 901`).
So, basically 9.2 and 9.4 behave the same.  Only 9.3 is different.  Is there a need to keep 9.3 (unreleased version)?

Also, wouldn't one make a minimal conditional (just 1 line is different --- and this only has an extra `Nothing`)?

2022-05-28 20:49 UTC, andreasabel commented on src/Extract.hs
> +
Why the empty line?

2022-05-28 20:55 UTC, andreasabel requested changes
Great work!

Question about the comparisons with GHC version 9.4:  Usually, one would think that the new API is already used with the development version, which is 9.3.  So, shouldn't one compare the GHC version with 9.3 rather than 9.4?
I seem to remember that most of the old conditionals were this way...

2022-05-28 20:58 UTC, andreasabel commented
> Yeah. I'm not sure how to enable that since it's an alpha prerelease.

I piggy-back on Haskell-CI which supports GHC 9.4.1 alpha.  It looks like this:
https://github.com/haskell-github/github/blob/299ad10ea23d9df5819f5e64dec9dd664ba74bb7/.github/workflows/haskell-ci.yml#L35-L39
https://github.com/haskell-github/github/blob/299ad10ea23d9df5819f5e64dec9dd664ba74bb7/.github/workflows/haskell-ci.yml#L100
Etc. look for `HEADHACKAGE`...

2022-07-29 21:50 UTC, martijnbastiaan commented
@parsonsmatt Did you manage to get it running on 9.4? I've managed to port over `doctest-parallel`. If you need inspiration you can pick it from this PR https://github.com/martijnbastiaan/doctest-parallel/pull/43. This biggest change is the `fromHsType`. (Other than that I've monomorphized some code which makes it easier to debug, which you can ignore.)

2022-08-12 06:21 UTC, andreasabel commented
@parsonsmatt @sol  Now that GHC 9.4.1 is out, any chance to finishing this PR?

2022-08-22 18:02 UTC, parsonsmatt commented
I may pick this back up again, but getting `yesod` on 9.4 is my bigger priority

2022-09-09 14:23 UTC, yaitskov commented
I tried to build doctest from this PR with 9.4.2 and detected compilation errors, not just a failing test:

```
[10 of 16] Compiling Extract          ( src/Extract.hs, dist/build/Extract.o, dist/build/Extract.dyn_o )

src/Extract.hs:337:37: error:
    • Couldn't match type ‘WithHsDocIdentifiers HsDocString GhcPs’
                     with ‘HsDocString’
      Expected: HsDocString
        Actual: HsDoc GhcPs
    • In the second argument of ‘L’, namely ‘ldoc’
      In the expression: L noSrcSpan ldoc
      In the expression: (Nothing, L noSrcSpan ldoc)
    |
337 |             ([(Nothing, L noSrcSpan ldoc)], False)
    |                                     ^^^^

src/Extract.hs:339:13: error:
    • Found hole: _g :: ([(Maybe String, LHsDocString)], Bool)
      Or perhaps ‘_g’ is mis-spelled, or not in scope
    • In a case alternative: _ -> _g
      In the second argument of ‘($)’, namely
        ‘case sig of
           TypeSig _ lhs
                   (HsWC _ (L _ (HsSig _ _ (L _ (HsDocTy _ _ (L _ ldoc))))))
             -> ([(Nothing, L noSrcSpan ldoc)], False)
           _ -> _g’
      In the expression:
        Debug.trace "in fromSigDecl"
          $ case sig of
              TypeSig _ lhs
                      (HsWC _ (L _ (HsSig _ _ (L _ (HsDocTy _ _ (L _ ldoc))))))
                -> ([(Nothing, L noSrcSpan ldoc)], False)
              _ -> _g
    • Relevant bindings include
        sig :: Sig GhcPs (bound at src/Extract.hs:335:17)
        fromSigDecl :: Selector (Sig GhcPs) (bound at src/Extract.hs:335:5)

```

2022-10-18 00:43 UTC, ysangkok commented
I think this can be closed now that #382 was merged?

2022-10-18 02:23 UTC, closed without merging