Add GHC 9.10 support
sol/doctest pull request #421
Opened 2024-05-20 15:06 UTC by sellout

2024-05-21 08:13 UTC, sol requested changes

2024-05-21 08:13 UTC, sol commented on .github/workflows/build.yml
>            - os: macos-latest
This also needs to be changed to `macos-12`, as later versions of the runner image don't include `ghc` / `ghcup` anymore.

2024-05-21 08:14 UTC, sol requested changes
@sellout thanks for looking into this.  I think one test case is failing, if you can fix this (possibly needs, CPP, not sure), then this is good to merge.

2024-05-31 05:08 UTC, sellout commented
Sorry for the delay here. I was running into other test failures and didn’t have time to dig in. But I just went over it again, and I was running the tests incorrectly 🤦

2024-05-31 15:12 UTC, sellout commented
Sorry, fixing this with some broader local testing before I push again.

2024-05-31 15:37 UTC, sellout commented
Ok, pushed a new version of the fix. I had had the wrong version in a conditional, so it worked with GHC 9.10, but I broke older versions. Tested 9.4, 9.6, 9.8, and 9.10 this time around.

2024-06-02 11:31 UTC, sol approved these changes

2024-06-02 11:31 UTC, merged

2024-06-02 11:32 UTC, sol commented
Thanks 🎉