Prepare 0.22.9 release
sol/doctest pull request #449
Opened 2024-07-30 09:35 UTC by hsyl20

2024-07-30 11:22 UTC, hsyl20 commented
Somehow `cabal-doctest` doesn't find the new version of `doctest`. Isn't it because we pass `--ignore-project`?

2024-07-31 06:51 UTC, sol commented
> Somehow `cabal-doctest` doesn't find the new version of `doctest`. Isn't it because we pass `--ignore-project`?

Yes, that's expected.  The `cabal-doctest` workflow will fail whenever you do a release. Build failures for `cabal-coctest` are informational for that reason, they don't block a merge. I don't have a better solution for this yet.

2024-07-31 08:31 UTC, hsyl20 commented
This MR now includes the fix for the testsuite to pass. See https://github.com/sol/doctest/pull/448#issuecomment-2259952049

2024-07-31 10:03 UTC, sol commented
> With the right command line to run tests (I was using cabal test) I only get 1 failure with 9.10:

It's still not clear to me why this failure does not show up on CI.  Is this maybe depending on the value of TERM or something? On the one hand, this would make sense, on the other hand you shouldn't look at TERM at all if the output is not going to a terminal.

2024-07-31 12:59 UTC, sol commented
> on the other hand you shouldn't look at TERM at all if the output is not going to a terminal.

The reason why `ghci` prints those links in the first place is because of

https://github.com/sol/doctest/blob/f930eaae60ecdd13a1e933248dbd1c886fbdc399/src/Language/Haskell/GhciWrapper.hs#L64

Redirection of `stderr` is only done after `ghci` has started. At that point GHC already decided that output is going to a terminal, hence we see the links. 

A proper solution would be to do something along the lines of: https://github.com/hspec/sensei/blob/5c11026fa48e13ea1c351ab882765eb0966f2e97/src/Language/Haskell/GhciWrapper.hs#L63-L71

But things are actually even more complicated than that (not elaborating on it now, but if you want to work on it then please ask and I'll give the full story). That's why we are going with #448 for now.

2024-07-31 13:05 UTC, sol commented on src/GhcUtil.hs
> +  let dynflags = dynflags' { useErrorLinks = Never }
@hsyl20 we need to differentiate between:

1. Extracting comments with the GHCAPI.
2. Evaluating expressions with GHCi.

For (1) we want the exact same error behavior as GHC, including colors and hyperlinks.

For (2) we don't want colors and hyperlinks.54 OK

2024-07-31 13:09 UTC, sol requested changes
Please include only the version bump in this PR. (see my other comments)

2024-07-31 14:41 UTC, hsyl20 commented
I've removed the other commit. I won't have much time to work on this soon either.

2024-07-31 22:17 UTC, merged