Change haskell setup action in CI and minor adjustments
sol/doctest pull request #461
Opened 2024-12-21 14:25 UTC by albertodvp

Hi :)

I'm testing the library with GHC912 and the `haskell-actions` one is already supporting that. In this PR I did some updates to the GHA build job, in particular:

1. I've substituted the [hspec setup action](https://github.com/hspec/setup-haskell) with the [haskell-actions one](https://github.com/haskell-actions/setup). **Note**: `cabal update` is done by default by the used action.

2. Replaced `macOS-12` environment which is deprecated.

3. I've also run [actionlint](https://github.com/rhysd/actionlint) and addressed those issues. Here is the output of that tool:
```
.github/workflows/build.yml:121:9: shellcheck reported issue in this script: SC2046:warning:1:12: Quote this to prevent word splitting [shellcheck]
    |
121 |       - run: cabal exec $(cabal list-bin spec)
    |         ^~~~
.github/workflows/build.yml:136:15: the runner of "actions/checkout@v3" action is too old to run on GitHub Actions. update the action's version to fix this issue [action]
    |
136 |       - uses: actions/checkout@v3
    |               ^~~~~~~~~~~~~~~~~~~
```

---
I've prepared this during this event
[![Open Source Saturday](https://img.shields.io/badge/%E2%9D%A4%EF%B8%8F-open%20source%20saturday-F64060.svg)](https://lu.ma/open-source-saturday-torino)

2024-12-21 23:30 UTC, sol commented
Hi 👋 

> I'm testing the library with GHC912 and the `haskell-actions` one is already supporting that.

I think `hspec/setup-haskell` also already supported GHC 9.12.1.  What it did not support was recent versions of macOS, as GitHub dropped support for `ghcup` from the macOS runner images.  I fixed this in https://github.com/hspec/setup-haskell/commit/cd264c751942b6dfa2784c5493a6a0dc22315a56.

> 1. I've substituted the [hspec setup action](https://github.com/hspec/setup-haskell) with the [haskell-actions one](https://github.com/haskell-actions/setup). **Note**: `cabal update` is done by default by the used action.

I'm not interested in this change at this point.

> ```
> .github/workflows/build.yml:121:9: shellcheck reported issue in this script: SC2046:warning:1:12: Quote this to prevent word splitting [shellcheck]
>     |
> 121 |       - run: cabal exec $(cabal list-bin spec)
>     |         ^~~~
> .github/workflows/build.yml:136:15: the runner of "actions/checkout@v3" action is too old to run on GitHub Actions. update the action's version to fix this issue [action]
>     |
> 136 |       - uses: actions/checkout@v3
>     |               ^~~~~~~~~~~~~~~~~~~
> ```

This looks good. Can you rebase on `main`?

2024-12-22 00:12 UTC, albertodvp commented
Thanks for the review. Assuming I'm understanding correctly, I've:
- removed the haskell-actions/setup 
- kept the linting suggestions

Does it look good? It it does, I would to rename the PR with something like: **Apply lint to GHA** (I'm not doing that by myself to avoid confusion)

2024-12-22 02:14 UTC, sol requested changes

2024-12-22 02:14 UTC, sol commented on .github/workflows/build.yml
> -          # - 9.2.1
This documents which versions have CI issues.  For that reason I would like to keep these.

2024-12-22 02:14 UTC, sol commented on .github/workflows/build.yml
> -          # - 9.6.1
Same here.

2024-12-22 02:14 UTC, sol commented on .github/workflows/build.yml
> -            # ghc: system
Same here.

2024-12-22 02:14 UTC, sol commented on .github/workflows/build.yml
> +      - run: cabal exec "$(cabal list-bin spec)"
👍

2024-12-22 02:14 UTC, sol commented on .github/workflows/build.yml
> +      - uses: actions/checkout@v4
👍

2024-12-22 02:18 UTC, sol commented
> Thanks for the review. Assuming I'm understanding correctly, I've:
> 
> * removed the haskell-actions/setup
> * kept the linting suggestions
> * (rebased)

Yes exactly 👍 

> I would to rename the PR to something like: **Apply lint to GHA**

Yes, please go ahead. But instead of using an acronym, please spell it out, also in the commit message.

2024-12-22 14:29 UTC, sol approved these changes

2024-12-22 14:31 UTC, sol commented
Thanks a lot for your contribution.

2024-12-22 14:50 UTC, merged