Add support for GHC912
sol/doctest pull request #462
Opened 2024-12-21 15:15 UTC by albertodvp

Add support for GHC912.

Depends on #461 

---
I've prepared this during this event :)
[![Open Source Saturday](https://img.shields.io/badge/%E2%9D%A4%EF%B8%8F-open%20source%20saturday-F64060.svg)](https://lu.ma/open-source-saturday-torino)

2024-12-21 23:32 UTC, sol commented
Hey @albertodvp 👋

Thanks for looking into this. Please rebase your changes on `main`.

2024-12-22 03:09 UTC, sol requested changes
Other than my comment, this looks good 👍

Please make sure to squash all your  changes into a single commit.

2024-12-22 14:18 UTC, sol requested changes
Please address that last comment,

2024-12-22 14:18 UTC, sol commented on package.yaml
> +    ghc: ">= 8.0 && < 9.13"
This was actually correct before. It should be `< 9.14` so that Doctest can be used with development versions of GHC.

2024-12-22 14:20 UTC, sol commented on package.yaml
> +    ghc: ">= 8.0 && < 9.13"
I'm gonna take care of it.

2024-12-22 14:26 UTC, sol approved these changes

2024-12-22 14:31 UTC, sol commented
Again, thanks a lot for your contribution.

2024-12-22 14:35 UTC, albertodvp commented
Thank you for the patience ☺️

2024-12-22 14:46 UTC, merged